export const GET_NASA ='GET_NASA';
export const  GET_IMAGES ='GET_IMAGES';
export const  SEARCH_IMAGES ='SEARCH_IMAGES';
export const GET_POSTS ='GET_POSTS';
export const GET_POST ='GET_POST';
export const GET_ALBUMS ='GET_ALBUMS';
export const LOADING_DATA='LOADING_DATA';
export const  GET_COMMENTS='GET_COMMENTS';
export const GET_PHOTOS ='GET_PHOTOS';
